"""LCM Summarization via ModelProvider with circuit breaker.

Handles the actual LLM calls for summarizing messages and summary nodes,
with a circuit breaker that trips after consecutive failures to prevent
cascading timeouts during compaction.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from prometheus.memory.lcm_types import MessagePart, SummaryNode
from prometheus.providers.base import ApiMessageRequest, ModelProvider

if TYPE_CHECKING:
    from prometheus.engine.messages import ConversationMessage

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Circuit breaker exception
# ---------------------------------------------------------------------------


class LCMCircuitBreakerOpen(Exception):
    """Raised when the summarization circuit breaker has tripped.

    This happens after ``_MAX_CONSECUTIVE_FAILURES`` (default 3) consecutive
    LLM call failures.  Callers should skip compaction and retry later.
    """


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_MESSAGE_SUMMARY_PROMPT = (
    "You are a conversation compactor.  Summarize the following conversation "
    "messages into a concise paragraph.  Preserve:\n"
    "  - Key decisions and conclusions\n"
    "  - Code changes, file paths, and technical details\n"
    "  - Action items and open questions\n"
    "  - Important names, entities, and relationships\n\n"
    "Be factual and terse.  Do NOT add commentary or opinions.\n\n"
    "Messages:\n{messages}"
)

_NODE_SUMMARY_PROMPT = (
    "You are a conversation compactor performing a higher-level merge.  "
    "Summarize the following summaries into a single, more compressed paragraph.  "
    "Preserve:\n"
    "  - Key decisions and conclusions\n"
    "  - Code changes, file paths, and technical details\n"
    "  - Action items and open questions\n"
    "  - Important names, entities, and relationships\n\n"
    "Be factual and terse.  Do NOT repeat yourself or add commentary.\n\n"
    "Summaries:\n{summaries}"
)

# ---------------------------------------------------------------------------
# Summarizer
# ---------------------------------------------------------------------------

_MAX_CONSECUTIVE_FAILURES = 3


class LCMSummarizer:
    """Summarizes messages and summary nodes via a :class:`ModelProvider`.

    Implements a simple circuit breaker: after ``_MAX_CONSECUTIVE_FAILURES``
    consecutive failed LLM calls the breaker opens and all subsequent calls
    raise :class:`LCMCircuitBreakerOpen` until :meth:`reset` is called.
    """

    def __init__(
        self,
        provider: ModelProvider,
        *,
        model: str = "default",
        max_retries: int = 2,
    ) -> None:
        self._provider = provider
        self._model = model
        self._max_retries = max_retries
        self._consecutive_failures: int = 0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def summarize_messages(self, messages: list[MessagePart]) -> str:
        """Produce a concise summary of raw conversation messages.

        Args:
            messages: Ordered list of :class:`MessagePart` instances.

        Returns:
            A summary string generated by the model.

        Raises:
            LCMCircuitBreakerOpen: If the breaker has tripped.
        """
        formatted = "\n".join(
            f"[{m.role}] {m.content}" for m in messages
        )
        prompt = _MESSAGE_SUMMARY_PROMPT.format(messages=formatted)
        return await self._call_model(prompt)

    async def summarize_summaries(self, summaries: list[SummaryNode]) -> str:
        """Merge multiple summary nodes into a higher-depth summary.

        Args:
            summaries: Ordered list of :class:`SummaryNode` instances.

        Returns:
            A higher-level summary string.

        Raises:
            LCMCircuitBreakerOpen: If the breaker has tripped.
        """
        formatted = "\n---\n".join(
            f"[depth={s.depth}] {s.summary_text}" for s in summaries
        )
        prompt = _NODE_SUMMARY_PROMPT.format(summaries=formatted)
        return await self._call_model(prompt)

    def reset(self) -> None:
        """Reset the circuit breaker after a recovery period."""
        self._consecutive_failures = 0

    @property
    def circuit_open(self) -> bool:
        """Return ``True`` if the breaker is currently open."""
        return self._consecutive_failures >= _MAX_CONSECUTIVE_FAILURES

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _call_model(self, prompt: str) -> str:
        """Call the model with retries and circuit breaker logic.

        Raises:
            LCMCircuitBreakerOpen: If the breaker is already open.
            RuntimeError: If all retries are exhausted (also trips the breaker).
        """
        if self.circuit_open:
            raise LCMCircuitBreakerOpen(
                f"Circuit breaker open after {self._consecutive_failures} "
                "consecutive failures.  Skipping summarization."
            )

        last_error: Exception | None = None
        for attempt in range(1 + self._max_retries):
            try:
                # Build a minimal single-user-turn request.
                from prometheus.engine.messages import ConversationMessage

                request = ApiMessageRequest(
                    model=self._model,
                    messages=[
                        ConversationMessage(role="user", content=prompt),
                    ],
                    system_prompt=(
                        "You are a precise summarization engine.  "
                        "Respond ONLY with the requested summary."
                    ),
                    max_tokens=1024,
                )

                # Consume the stream and extract the complete text.
                full_text = ""
                async for event in self._provider.stream_message(request):
                    from prometheus.providers.base import (
                        ApiMessageCompleteEvent,
                        ApiTextDeltaEvent,
                    )

                    if isinstance(event, ApiTextDeltaEvent):
                        full_text += event.text
                    elif isinstance(event, ApiMessageCompleteEvent):
                        # If the complete event carries a text content block,
                        # prefer that as the authoritative response.
                        if hasattr(event.message, "content"):
                            content = event.message.content
                            if isinstance(content, str) and content:
                                full_text = content
                            elif isinstance(content, list):
                                # Extract text from content blocks
                                parts = []
                                for block in content:
                                    if hasattr(block, "text"):
                                        parts.append(block.text)
                                if parts:
                                    full_text = "".join(parts)

                if not full_text.strip():
                    raise RuntimeError("Model returned empty summary")

                # Success -- reset breaker.
                self._consecutive_failures = 0
                return full_text.strip()

            except LCMCircuitBreakerOpen:
                raise
            except Exception as exc:
                last_error = exc
                logger.warning(
                    "LCM summarization attempt %d/%d failed: %s",
                    attempt + 1,
                    1 + self._max_retries,
                    exc,
                )

        # All retries exhausted -- increment breaker counter.
        self._consecutive_failures += 1
        logger.error(
            "LCM summarization failed after %d attempts (consecutive failures: %d/%d)",
            1 + self._max_retries,
            self._consecutive_failures,
            _MAX_CONSECUTIVE_FAILURES,
        )
        raise RuntimeError(
            f"Summarization failed after {1 + self._max_retries} attempts: {last_error}"
        ) from last_error
